name: CI Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image
        run: make build
      - name: Linting
        run: make lint
      - name: Unit Test
        run: make unittest
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the Image
        run: |
          DATA_HUB_API_IMAGE_REPO=ghcr.io/elifesciences/data-hub-api_unstable \
          DATA_HUB_API_IMAGE_TAG=latest \
          make build docker-push